import { Lesson, LessonModule } from '../models/types';

export const modules: LessonModule[] = [
  {
    id: 1,
    title: 'REST Basics',
    description: 'Learn fundamental HTTP methods and how to read API responses. Start here if you are new to REST APIs.',
  },
  {
    id: 2,
    title: 'CRUD Operations',
    description: 'Master Create, Read, Update, and Delete operations - the building blocks of any REST API.',
  },
  {
    id: 3,
    title: 'Relationships & Nested Resources',
    description: 'Explore how resources relate to each other through nested routes and business validation.',
  },
  {
    id: 4,
    title: 'Advanced Operations',
    description: 'Learn about transfers, idempotency, cross-currency operations, and real-world API patterns.',
  },
  {
    id: 5,
    title: 'Query & Pagination',
    description: 'Master filtering, sorting, pagination, and reading response headers for metadata.',
  },
  {
    id: 6,
    title: 'HTTP Deep Dive',
    description: 'Explore advanced HTTP concepts: content types, error formats, ETags, and CORS.',
  },
];

export const lessons: Lesson[] = [
  // Module 1: REST Basics
  {
    id: 1,
    moduleId: 1,
    title: 'Your First GET Request',
    description: 'The GET method is used to retrieve data from a server. It\'s the most common HTTP method - every time you visit a webpage, your browser sends a GET request.',
    task: 'Make a GET request to `/currencies` to retrieve the list of all available currencies. Observe the response structure.',
    hint: 'In Swagger UI, find the Currencies section, expand "GET /currencies", and click "Try it out" then "Execute".',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/currencies$',
  },
  {
    id: 2,
    moduleId: 1,
    title: 'Path Parameters',
    description: 'Path parameters are part of the URL and identify a specific resource. They appear as placeholders in the path like `/currencies/{code}`. Unlike query parameters, they are required.',
    task: 'Retrieve the details of a single currency by its code. Try fetching the US Dollar using its code `USD`.',
    hint: 'Use GET /currencies/USD. The currency code goes directly in the URL path.',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/currencies/[A-Z]+$',
  },
  {
    id: 3,
    moduleId: 1,
    title: 'Query Parameters',
    description: 'Query parameters appear after `?` in the URL and are used to filter, sort, or modify the response. They are optional and use the format `?key=value&key2=value2`.',
    task: 'Filter the currencies list to show only cryptocurrencies. Use the `type` query parameter with value `crypto`.',
    hint: 'Use GET /currencies?type=crypto. In Swagger UI, fill in the "type" parameter field before executing.',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/currencies',
  },
  {
    id: 4,
    moduleId: 1,
    title: 'Reading HTTP Status Codes',
    description: 'Every HTTP response includes a status code. Common ones: 200 (OK), 201 (Created), 204 (No Content), 400 (Bad Request), 404 (Not Found), 422 (Unprocessable Entity), 500 (Server Error). The status code tells you whether your request succeeded and, if not, what went wrong.',
    task: 'What HTTP status code do you get when you successfully retrieve the list of currencies?',
    hint: 'Look at the "Responses" section in Swagger UI after executing a GET request. The status code appears next to the response body.',
    verificationType: 'quiz',
    expectedAnswer: '200',
  },
  {
    id: 5,
    moduleId: 1,
    title: 'Handling 404 Not Found',
    description: 'When you request a resource that doesn\'t exist, the API returns a 404 status code. This is one of the most important error codes to understand. The response body usually contains an error message explaining what was not found.',
    task: 'Try to fetch a currency with code `XYZ` (which doesn\'t exist). What error code and message do you get?',
    hint: 'Use GET /currencies/XYZ and observe both the status code (404) and the error response body structure.',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/currencies/',
  },

  // Module 2: CRUD Operations
  {
    id: 6,
    moduleId: 2,
    title: 'Creating a Resource (POST)',
    description: 'The POST method creates a new resource. You send data in the request body (usually JSON) and the server responds with the created resource including a generated ID. The response status code is 201 (Created).',
    task: 'Create a new bank account by sending a POST request to `/accounts`. Use this body: `{"name": "My Learning Account", "ownerName": "Student", "currency": "USD", "type": "checking"}`',
    hint: 'In Swagger UI, expand POST /accounts, click "Try it out", paste the JSON body, and execute. Note the 201 status code and the generated ID in the response.',
    verificationType: 'state',
  },
  {
    id: 7,
    moduleId: 2,
    title: 'Retrieving Your Resource',
    description: 'After creating a resource, you can retrieve it using its ID. The ID is typically returned in the creation response. This follows the REST principle that every resource has a unique URL.',
    task: 'Copy the `id` from the account you just created and use GET `/accounts/{id}` to retrieve it.',
    hint: 'The ID was in the response when you created the account. Use it in the path: GET /accounts/your-id-here',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/accounts/.+$',
  },
  {
    id: 8,
    moduleId: 2,
    title: 'Full Update with PUT',
    description: 'PUT replaces the entire resource. You must send ALL required fields, even the ones you don\'t want to change. If you omit a field, it may be reset to its default. Think of PUT as "replace this resource with this new version".',
    task: 'Update your account using PUT `/accounts/{id}`. Change the name to "Updated Account" but keep all other required fields (ownerName, currency, type).',
    hint: 'Send ALL required fields: `{"name": "Updated Account", "ownerName": "Student", "currency": "USD", "type": "checking"}`. Missing a field will cause a 400 error.',
    verificationType: 'exploration',
    expectedMethod: 'PUT',
    expectedEndpoint: '^/accounts/.+$',
  },
  {
    id: 9,
    moduleId: 2,
    title: 'Partial Update with PATCH',
    description: 'PATCH updates only the fields you specify, leaving everything else unchanged. This is more efficient than PUT when you only need to change one or two fields. Not all APIs support PATCH, but it\'s becoming standard.',
    task: 'Use PATCH `/accounts/{id}` to change only the status of the frozen account (acc-005) to "active". Send only `{"status": "active"}`.',
    hint: 'PATCH /accounts/acc-005 with body `{"status": "active"}`. Notice you don\'t need to send name, ownerName, etc.',
    verificationType: 'exploration',
    expectedMethod: 'PATCH',
    expectedEndpoint: '^/accounts/.+$',
  },
  {
    id: 10,
    moduleId: 2,
    title: 'Deleting a Resource',
    description: 'DELETE removes a resource. A successful deletion returns 204 (No Content) - meaning the server processed your request but has nothing to send back. Some APIs return the deleted resource instead.',
    task: 'First, create a new account with 0 balance, then delete it using DELETE `/accounts/{id}`. What status code do you get?',
    hint: 'Create an account with no initialBalance (defaults to 0), then DELETE /accounts/{id}. The response should be 204 with an empty body.',
    verificationType: 'quiz',
    expectedAnswer: '204',
  },
  {
    id: 11,
    moduleId: 2,
    title: 'Gone Forever',
    description: 'Once a resource is deleted, trying to access it should return 404. This confirms the resource no longer exists. In some APIs, you might get 410 (Gone) instead, which means "this used to exist but was deleted".',
    task: 'Try to GET the account you just deleted. Verify you receive a 404 response.',
    hint: 'Use the same ID from the account you deleted. GET /accounts/{deleted-id} should return 404.',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/accounts/.+$',
  },

  // Module 3: Relationships & Nested Resources
  {
    id: 12,
    moduleId: 3,
    title: 'Depositing Money',
    description: 'Transactions belong to accounts - this is a parent-child relationship. The URL reflects this: `/accounts/{id}/transactions`. Creating a transaction modifies the parent account\'s balance.',
    task: 'Deposit $1000 into account acc-001 by POSTing to `/accounts/acc-001/transactions` with body: `{"type": "deposit", "amount": 1000, "description": "My first deposit"}`',
    hint: 'POST /accounts/acc-001/transactions. The account balance will increase by the deposit amount. Check the balanceAfter field in the response.',
    verificationType: 'state',
  },
  {
    id: 13,
    moduleId: 3,
    title: 'Listing Nested Resources',
    description: 'Nested routes let you access child resources through their parent. GET `/accounts/{id}/transactions` returns only transactions for that specific account, not all transactions in the system.',
    task: 'List all transactions for account acc-001 using GET `/accounts/acc-001/transactions`.',
    hint: 'GET /accounts/acc-001/transactions. Compare with acc-002 or acc-003 to see different transactions per account.',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/accounts/.+/transactions$',
  },
  {
    id: 14,
    moduleId: 3,
    title: 'Combining Path and Query Parameters',
    description: 'You can use query parameters with nested routes too. For example, filtering a specific account\'s transactions by type combines a path parameter (account ID) with a query parameter (type).',
    task: 'List only the "fee" transactions for account acc-001. Use the `type` query parameter.',
    hint: 'GET /accounts/acc-001/transactions?type=fee. This combines the path param (acc-001) with query param (type=fee).',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/accounts/.+/transactions',
  },
  {
    id: 15,
    moduleId: 3,
    title: 'Business Rule Validation (422)',
    description: 'APIs enforce business rules. When a request is technically valid JSON but violates a business rule, the API returns 422 (Unprocessable Entity). This is different from 400 (Bad Request) which means the request format itself is wrong.',
    task: 'Try to withdraw $999,999 from account acc-001 (more than its balance). What error code do you get?',
    hint: 'POST /accounts/acc-001/transactions with `{"type": "withdrawal", "amount": 999999}`. The INSUFFICIENT_FUNDS error has details showing available vs requested.',
    verificationType: 'quiz',
    expectedAnswer: '422',
  },

  // Module 4: Advanced Operations
  {
    id: 16,
    moduleId: 4,
    title: 'Making a Transfer',
    description: 'Transfers are an "action" resource - they represent an operation, not just data. POSTing a transfer triggers a complex workflow: validating both accounts, checking funds, calculating exchange rates, and creating transactions on both sides.',
    task: 'Create a transfer of $100 from acc-001 to acc-003. POST to `/transfers` with: `{"sourceAccountId": "acc-001", "destinationAccountId": "acc-003", "amount": 100}`',
    hint: 'After the transfer, check both accounts\' balances - acc-001 should decrease and acc-003 should increase. Also check /accounts/acc-001/transactions for the new transfer_out transaction.',
    verificationType: 'state',
  },
  {
    id: 17,
    moduleId: 4,
    title: 'Idempotency Keys',
    description: 'Idempotency means "doing the same thing twice has the same effect as doing it once". In payments, this prevents duplicate charges. By sending an `idempotencyKey`, the API will recognize a repeated request and return the original result instead of processing it again.',
    task: 'Create a transfer with `"idempotencyKey": "my-unique-key-123"`. Then send the exact same request again. Notice the second request returns 200 (not 201) with the original transfer.',
    hint: 'First POST returns 201 (created). Second identical POST returns 200 (already exists). The transfer ID will be the same both times.',
    verificationType: 'exploration',
    expectedMethod: 'POST',
    expectedEndpoint: '^/transfers$',
  },
  {
    id: 18,
    moduleId: 4,
    title: 'Account Status Enforcement',
    description: 'Real APIs enforce state-based rules. A frozen account cannot send or receive transfers. The API should return a clear error explaining why the operation was rejected and what the current state is.',
    task: 'Try to create a transfer FROM the frozen account (acc-005). What error code and message do you get?',
    hint: 'POST /transfers with sourceAccountId "acc-005". The error response includes the account status in the details field.',
    verificationType: 'exploration',
    expectedMethod: 'POST',
    expectedEndpoint: '^/transfers$',
  },
  {
    id: 19,
    moduleId: 4,
    title: 'Cross-Currency Transfer',
    description: 'When transferring between accounts with different currencies, the API automatically applies the exchange rate. The `amount` is in the source currency, and `convertedAmount` shows what the recipient gets.',
    task: 'Transfer $500 from acc-001 (USD) to acc-002 (EUR). Examine the response to see the exchangeRate and convertedAmount fields.',
    hint: 'POST /transfers with sourceAccountId "acc-001" and destinationAccountId "acc-002". The response shows both the original amount in USD and the converted amount in EUR.',
    verificationType: 'state',
  },

  // Module 5: Query & Pagination
  {
    id: 20,
    moduleId: 5,
    title: 'Pagination',
    description: 'APIs paginate large collections to avoid sending thousands of records at once. Common patterns: limit/offset (skip N items, take M items), cursor-based, or page-based. This API uses limit/offset.',
    task: 'List transactions for acc-001 with `limit=2&offset=0`, then with `offset=2` to get the next page. Compare the results.',
    hint: 'GET /accounts/acc-001/transactions?limit=2&offset=0 then ?limit=2&offset=2. Check the `meta` object - it tells you total count and current position.',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/accounts/.+/transactions',
  },
  {
    id: 21,
    moduleId: 5,
    title: 'Date Range Filtering',
    description: 'Many APIs support filtering by date range using `from` and `to` query parameters. Dates are usually in ISO 8601 format (e.g., 2024-01-01T00:00:00Z).',
    task: 'Generate an account summary report for January-February 2024 only. Use `/reports/account-summary?from=2024-01-01T00:00:00Z&to=2024-02-28T23:59:59Z`',
    hint: 'GET /reports/account-summary with the date parameters. Compare the transaction counts with a report without dates to see the filtering effect.',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/reports/account-summary',
  },
  {
    id: 22,
    moduleId: 5,
    title: 'Sorting',
    description: 'Sort parameters let you control the order of results. Common pattern: `sortBy` (field name) + `order` (asc/desc). Not all fields are sortable - the API documentation tells you which ones are.',
    task: 'List transactions for acc-001 sorted by amount in descending order (largest first). Use `sortBy=amount&order=desc`.',
    hint: 'GET /accounts/acc-001/transactions?sortBy=amount&order=desc. The first transaction should have the highest amount.',
    verificationType: 'exploration',
    expectedMethod: 'GET',
    expectedEndpoint: '^/accounts/.+/transactions',
  },
  {
    id: 23,
    moduleId: 5,
    title: 'Reading Response Headers',
    description: 'HTTP responses contain headers with metadata. APIs often include custom headers like `X-Total-Count` (total records), `X-Report-Generated-At`, or `Link` (pagination URLs). These provide information beyond the body.',
    task: 'Request the transaction report from `/reports/transactions` and find the `X-Report-Generated-At` and `X-Total-Count` headers in the response. What do they tell you?',
    hint: 'In Swagger UI, after executing the request, look at the "Response headers" section below the response body. Custom headers start with X-.',
    verificationType: 'quiz',
    expectedAnswer: 'X-Total-Count',
  },

  // Module 6: HTTP Deep Dive
  {
    id: 24,
    moduleId: 6,
    title: 'Content-Type Header',
    description: 'The Content-Type header tells the server what format your request body is in. REST APIs typically expect `application/json`. Sending the wrong Content-Type can cause the server to reject or misparse your request.',
    task: 'What Content-Type header should you send when creating an account? (Answer with the full MIME type)',
    hint: 'Look at the request headers in Swagger UI when you create an account. The standard Content-Type for JSON APIs is...',
    verificationType: 'quiz',
    expectedAnswer: 'application/json',
  },
  {
    id: 25,
    moduleId: 6,
    title: 'Understanding Error Responses',
    description: 'Well-designed APIs return structured error responses. This API uses a consistent format: `{"error": {"code": "ERROR_CODE", "message": "Human-readable message", "details": {...}}}`. The code is machine-readable, the message is for humans.',
    task: 'Trigger three different error codes by: (1) requesting a non-existent account, (2) creating an account with missing fields, (3) trying to withdraw more than the balance. What are the three error codes?',
    hint: 'The three codes are: NOT_FOUND, VALIDATION_ERROR, and INSUFFICIENT_FUNDS. Notice how each has a different HTTP status code (404, 400, 422).',
    verificationType: 'quiz',
    expectedAnswer: 'NOT_FOUND',
  },
  {
    id: 26,
    moduleId: 6,
    title: 'ETags and Conditional Requests',
    description: 'ETags (Entity Tags) are a caching mechanism. The server sends an ETag header with a hash of the content. On subsequent requests, you can send `If-None-Match` with the ETag value. If the content hasn\'t changed, the server returns 304 (Not Modified) with no body, saving bandwidth.',
    task: 'GET /currencies and note the ETag header value. Then make the same request with header `If-None-Match` set to that ETag value. You should get a 304 response.',
    hint: 'First request: copy the ETag value from response headers (it looks like "abc123..."). Second request: add If-None-Match header with that value. The 304 response has no body.',
    verificationType: 'quiz',
    expectedAnswer: '304',
  },
  {
    id: 27,
    moduleId: 6,
    title: 'CORS Headers',
    description: 'CORS (Cross-Origin Resource Sharing) headers control which websites can call your API from a browser. Key headers: `Access-Control-Allow-Origin`, `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`. Without CORS, browsers block cross-origin API calls.',
    task: 'Make any GET request and look for the `Access-Control-Allow-Origin` header in the response. What is its value?',
    hint: 'Check the response headers section after any request. The `Access-Control-Allow-Origin: *` header means any website can call this API.',
    verificationType: 'quiz',
    expectedAnswer: '*',
  },
];
